0_otree_app/accounting/models.py
import itertools
import random
from django.core.validators import RegexValidator

from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


author = 'Victor van Pelt'

doc = """
Accounting Systems
"""


class Constants(BaseConstants):
    name_in_url = 'accounting_systems'
    players_per_group = 2
    num_rounds = 12

class Subsession(BaseSubsession):

    def creating_session(self):

        #Random Matching but fixed roles
        self.group_randomly(fixed_id_in_group=True)

        if self.round_number == 1:
            for g in self.get_groups():
                shockround = random.randint(4, 10)
                p1 = g.get_player_by_id(1)
                p1.participant.vars['shockround'] = shockround
                p1.participant.vars['e'] = c(self.session.config['e'])

        else:
            for g in self.get_groups():
                p1 = g.get_player_by_id(1)

                if self.round_number == p1.participant.vars['shockround']:
                    if p1.participant.vars['e'] == c(1):
                         p1.participant.vars['e'] = c(9)

                    else:
                         p1.participant.vars['e'] = c(1)

                else:
                    pass

        for g in self.get_groups():
            g.define_e_group()
            g.calculate_rpayoff1()
            g.define_shockround()

class Group(BaseGroup):

    e_g = models.CurrencyField()

    shockround = models.IntegerField(min=0, max=Constants.num_rounds, initial=None)

    r = models.FloatField(
        widget=widgets.SliderInput(attrs={'step': '0.01', 'style': 'width:500px'}, show_value=False),
        min=0,
        initial=None,
        max=1,
    )

    #For Slider check in Stage 1
    checkr = models.FloatField(blank=True, initial=None)

    #History counter for Stage 1
    historyc1 = models.IntegerField(blank=True, initial=0)

    #History counter for Stage 2
    historyc2 = models.IntegerField(blank=True, initial=0)

    #History counter for results P1
    historyr1 = models.IntegerField(blank=True, initial=0)

    #History counter for results P1
    historyr2 = models.IntegerField(blank=True, initial=0)

    payoff1 = models.CurrencyField()

    payoff1f = models.FloatField(
        widget=widgets.SliderInput(attrs={'step': '0.01', 'style': 'width:500px'}, show_value=False),
        min=5,
        initial=None,
        max=15,
        blank=True
    )

    #For Slider check in Stage 2
    checkpayoff1f = models.FloatField(blank=True, initial=None)

    payoff2 = models.CurrencyField()

    rpayoff1 = models.CurrencyField()

    payoff_p1 = models.CurrencyField()
    payoff_p2 = models.CurrencyField()

    def define_e_group(self):
        p1 = self.get_player_by_id(1)
        self.e_g = p1.participant.vars.get('e')

    def define_shockround(self):
        p1 = self.get_player_by_id(1)
        self.shockround = p1.participant.vars.get('shockround')

    def calculate_rpayoff1(self):
        p1 = self.get_player_by_id(1)
        self.rpayoff1 = c(15) - self.e_g
        #p1.participant.vars.get('e')

    def calculate_payoff1(self):
        if self.r == 1:
            self.payoff1 = None
        else :
            self.payoff1 = c(self.payoff1f)

    def calculate_payoff2(self):
        if self.r == 1:
            self.payoff2 = None
        else :
            self.payoff2 = -1 * (self.payoff1 - c(20))

    #For history table
    def calculate_payoff_p1_p2(self):
        if self.r == 1:
            self.payoff_p1 = self.r * (c(15) - self.e_g)
            self.payoff_p2 = self.r * c(5)
        else:
            self.payoff_p1 = self.r * (c(15) - self.e_g) + (1-self.r) * self.payoff1
            self.payoff_p2 = self.r * c(5) + (1-self.r) * self.payoff2

    def set_payoffs(self):
        p1 = self.get_player_by_id(1)
        p2 = self.get_player_by_id(2)
        if self.r == 1 :
            p1.payoff = self.r * (c(15) - self.e_g)
            p2.payoff = self.r * c(5)
        else :
            p1.payoff = self.r * (c(15) - self.e_g) + (1 - self.r) * self.payoff1
            p2.payoff = self.r * c(5) + (1 - self.r) * self.payoff2

class Player(BasePlayer):

    #Personal code
    tn = models.StringField(blank=False)
    # tn = models.CharField(
    #     blank=False,
    #     max_length=5,
    #     validators=
    #         [RegexValidator(
    #             r'^\d{5}$',
    #             message='Your personal code should have 5 digits',
    #             code='nomatch'
    #             )
    #         ]
    # )

    #Accept the conditions to participate
    accept_conditions = models.BooleanField(blank=False, widget=widgets.CheckboxInput)

    #Instruction1 checks
    Instr1a = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr1b = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr1c = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)

    #Instructions 2 check
    accept_payoffs = models.BooleanField(blank=False, widget=widgets.CheckboxInput)

    #Instruction2a checks
    Instr2aa = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr2ab = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)

    #Instruction2b checks
    Instr2ba = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr2bb = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr2bc = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)

    Fakeslider2 = models.FloatField(
        widget=widgets.SliderInput(attrs={'step': '0.01', 'style': 'width:450px'}, show_value=False),
        min=0,
        initial=0.5,
        blank=True,
        max=1
    )

    #Instruction3 checks
    Instr3a = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr3b = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr3c = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)
    Instr3d = models.IntegerField(blank=False, choices=[[1, 'True'],[2, 'False']], widget=widgets.RadioSelect)

    Fakeslider = models.FloatField(
        widget=widgets.SliderInput(attrs={'step': '0.01', 'style': 'width:450px'}, show_value=False),
        min=5,
        blank=True,
        initial=10,
        max=15
    )

    #History counter for Choice
    historyc = models.IntegerField(blank=True, initial=0)

    #History counter for Choice
    historyr = models.IntegerField(blank=True, initial=0)

    def get_partner(self):
        return self.get_others_in_group()[0]

0_otree_app/accounting/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

0_otree_app/accounting/templates/accounting/Information.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Important information
{% endblock %}

{% block content %}
<div class="instructions" style="height: 212px;">
    <ul>
        <li>
            Please read all information carefully and be aware that you cannot go back to previous screens.
        </li>
        <li>
            There are three stages in this study: an instruction stage, a decision stage, and lastly a questionnaire.
        </li>
        <li>
            Your decisions during the decision stage influence how many points you earn.
        </li>
        <li>
            Every 10 points is worth 0.60 EUR, and you will be paid within 3 weeks after this study.
        </li>
        <li>
            Students enrolled in Management Accounting (for IBA) also receive a bonus grade conform the syllabus.
        </li>
        <li>
            We expect no psychological discomfort nor physical injury. Also, there is no deception and your participation is voluntary.
        </li>
        <li>
            Your personal information will not be shared with anyone outside of our research team.
        </li>
    </ul>
</div>

{% formfield player.accept_conditions label="I have read and accept the conditions above." %}
<br>
{% next_button %}
{% endblock %}

0_otree_app/accounting/templates/accounting/Instructions1.html
{% extends "global/Page.html" %}
{% load otree staticfiles %}

{% block title %}
    Instructions
{% endblock %}

{% block content %}
    <span id="warningt"></span>
    <p></p>
    <div class="instructions" style="height: 138px">
    <ul>
        <li>
            You and the other participants in this session will interact with each other for <b>{{ Constants.num_rounds }}</b> periods.
        </li>
        <li>
            Half of the participants will fulfill the role of <b>Player 1</b> and the other half <b>Player 2</b>.
        </li>
        <li>
            You will be <b>Player {{ player.id_in_group }}</b>, and every period you will be randomly matched to another participant who plays <b>Player {{ player.get_partner.id_in_group }}</b>.
        </li>
        <li>
            In each period, <b>you</b> and <b>Player {{ player.get_partner.id_in_group }}</b> may make a decision that influences how many points both of you earn.
        </li>
    </ul>
</div>
    <p>
        Please evaluate the following statements.
    </p>
    <p>
        You fulfill the role of <b>Player {{ player.id_in_group }}</b>.
        {% formfield player.Instr1a label=None %}
    </p>
    <p>
        You will be matched to the same participant who plays <b>Player {{ player.get_partner.id_in_group }}</b> for <b>{{ Constants.num_rounds }}</b> periods.
        {% formfield player.Instr1b label=None %}
    </p>
    <p>
        {% if player.id_in_group == 1 %}
            In each period, only <b>you</b> make a decision that influences how many points you and <b>Player 2</b> earn.
        {% else %}
            In each period, only <b>Player 1</b> makes a decision that influences how many points <b>you</b> and <b>Player 1</b> earn.
        {% endif %}

        {% formfield player.Instr1c label=None %}
    </p>

    {% next_button %}

{% endblock %}

{% block scripts %}

    <script>
        setTimeout(function() {
            document.getElementById("warningt").innerHTML =
                '<div class="progress-bar-2" align="left" style="width: 250px; color: rgb(255,255,255); border-radius: 5px; background-color: rgb(228,28,28); height: 30px; text-align:center;"><b>Please finalize your answers</b></div>';
        }, 60000);
    </script>

{% endblock %}

0_otree_app/accounting/templates/accounting/Results.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Results
{% endblock %}

{% block content %}
    <span id="warningt"></span>
    <p></p>
{% if subsession.round_number == 1 %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar" role="progressbar" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ round_number_perc }}%; text-align:center">
            <span style="font-size:12pt;">Period</span>
        </div>
        <div class="progress-bar bg-transparent" role="progressbar" style="width:{{ round_number_perc }}%; text-align:left" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100">
            <span style="font-size:12pt; color:rgb(0, 0, 0);">{{ subsession.round_number }} of {{ Constants.num_rounds }}</span>
        </div>
    </div>
{% else %}
        <div class="progress" style="height: 30px;">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ round_number_perc }}%; text-align:center">
                <span style="font-size:12pt;">Period {{ subsession.round_number }} of {{ Constants.num_rounds }}</span>
            </div>
        </div>
{% endif %}
    <p></p>
{% if player.id_in_group == 1 %}
        <div class="instructions">
            {% if group.e_g == 1 %}
                The value for <b>c</b> was <b>{{ group.e_g|floatformat:0  }}</b> point.<br>
            {% else %}
                The value for <b>c</b> was <b>{{ group.e_g|floatformat:0  }}</b> points.<br>
            {% endif %}
                <b>You</b> (<b>Player 1</b>) chose to set <b>a</b> to <b>{{ group.r|floatformat:2 }}</b>.<br>
            {% if group.r == 1 %}
                <b>Player 2</b> could not choose <b>b1</b> and <b>b2</b>.
            {% else %}
                <b>Player 2</b> chose to set <b>b1</b> to <b>{{ group.payoff1|floatformat:2 }}</b>, and <b>b2</b> to <b>{{group.payoff2|floatformat:2}}</b>.
            {% endif %}
            <hr>
            <p>
                Payoffs in this period:
            </p>
            <b>You</b>: <b style="color: rgb(0,123,255);">{{ player.payoff|floatformat:2 }}</b> points<br>
            <b>Player {{ player.get_partner.id_in_group }}</b>: <b style="color: rgb(0,123,255);">{{ player.get_partner.payoff|floatformat:2 }}</b> points
        </div>
        <br>
        {% next_button %}
    <input type="hidden" name="historyr1" value="" id="id_historyr1"/>
    {% if subsession.round_number > 1 %}
  <div class="container">
  <button style="color: rgb(255,255,255); background-color: rgb(0,123,255);" type="button" class="btn btn-info" data-toggle="collapse" id="buttonh1" data-target="#demo">Click to view history</button>
  <div id="demo" class="collapse">
    <p>
    </p>
 <table class="table">
    <tr>
        <th>Period</th>
        <th>Results</th>
        <th>Payoffs</th>
    </tr>
    {% for p in player.in_previous_rounds %}
        <tr>
            <td>{{ p.round_number }}</td>
            <td>
                <b>c</b> = {{ p.group.e_g|floatformat:0 }}<br>
                <b>a</b> = {{ p.group.r|floatformat:2 }}<br>
                {% if p.group.r == 1 %}
                    {% if player.id_in_group == 1 %}
                        Player 2 could not choose <b>b1</b> and <b>b2</b>
                    {% else %}
                        You could not choose <b>b1</b> and <b>b2</b>
                    {% endif %}
                {% else %}
                    <b>b1</b> = {{ p.group.payoff1|floatformat:2 }}<br>
                    <b>b2</b> = {{ p.group.payoff2|floatformat:2 }}
                {%  endif %}
            </td>
            <td>
            {% if player.id_in_group == 1 %}
                <b>You</b>: {{ p.group.payoff_p1 }}<br>
                <b>Player 2</b>: {{ p.group.payoff_p2 }}
            {% else %}
                <b>Player 1</b>: {{ p.group.payoff_p1 }}<br>
                <b>You</b>: {{ p.group.payoff_p2 }}
            {% endif %}


            </td>
        </tr>
    {% endfor %}
</table>
 {% endif %}
  </div>
</div>
{% else %}
        <div class="instructions">
            {% if group.e_g == 1 %}
                The value for <b>c</b> was <b>{{ group.e_g|floatformat:0  }}</b> point.<br>
            {% else %}
                The value for <b>c</b> was <b>{{ group.e_g|floatformat:0  }}</b> points.<br>
            {% endif %}
                <b>Player 1</b> chose to set <b>a</b> to <b>{{ group.r|floatformat:2 }}</b>.<br>
            {% if group.r == 1 %}
                <b>You</b> (<b>Player 2</b>) could not choose <b>b1</b> and <b>b2</b>.
            {% else %}
                <b>You</b> (<b>Player 2</b>) chose to set <b>b1</b> to <b>{{ group.payoff1|floatformat:2 }}</b>, and <b>b2</b> to <b>{{group.payoff2|floatformat:2}}</b>.
            {% endif %}
            <hr>
            <p>
                Payoffs in this period:
            </p>
            <b>Player {{ player.get_partner.id_in_group }}</b>: <b style="color: rgb(0,123,255);">{{ player.get_partner.payoff|floatformat:2 }}</b> points<br>
            <b>You</b>: <b style="color: rgb(0,123,255);">{{ player.payoff|floatformat:2 }}</b> points
        </div>
    <br>
    {% next_button %}

    <input type="hidden" name="historyr2" value="" id="id_historyr2"/>
    {% if subsession.round_number > 1 %}
  <div class="container">
  <button style="color: rgb(255,255,255); background-color: rgb(0,123,255);" type="button" class="btn btn-info" data-toggle="collapse" id="buttonh2" data-target="#demo">Click to view history</button>
  <div id="demo" class="collapse">
    <p>
    </p>
 <table class="table">
    <tr>
        <th>Period</th>
        <th>Results</th>
        <th>Payoffs</th>
    </tr>
    {% for p in player.in_previous_rounds %}
        <tr>
            <td>{{ p.round_number }}</td>
            <td>
                <b>c</b> = {{ p.group.e_g|floatformat:0 }}<br>
                <b>a</b> = {{ p.group.r|floatformat:2 }}<br>
                {% if p.group.r == 1 %}
                    {% if player.id_in_group == 1 %}
                        Player 2 could not choose <b>b1</b> and <b>b2</b>
                    {% else %}
                        You could not choose <b>b1</b> and <b>b2</b>
                    {% endif %}
                {% else %}
                    <b>b1</b> = {{ p.group.payoff1|floatformat:2 }}<br>
                    <b>b2</b> = {{ p.group.payoff2|floatformat:2 }}
                {%  endif %}
            </td>
            <td>
            {% if player.id_in_group == 1 %}
                <b>You</b>: {{ p.group.payoff_p1 }}<br>
                <b>Player 2</b>: {{ p.group.payoff_p2 }}
            {% else %}
                <b>Player 1</b>: {{ p.group.payoff_p1 }}<br>
                <b>You</b>: {{ p.group.payoff_p2 }}
            {% endif %}


            </td>
        </tr>
    {% endfor %}
</table>
 {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}

    <script>
        $('#buttonh1').click(function() {
            $('#id_historyr1').val(1);
        });
    </script>
        <script>
        $('#buttonh2').click(function() {
            $('#id_historyr2').val(1);
        });
    </script>
    <script>
        setTimeout(function() {
            document.getElementById("warningt").innerHTML =
                '<div class="progress-bar-2" align="left" style="width: 250px; color: rgb(255,255,255); border-radius: 5px; background-color: rgb(228,28,28); height: 30px; text-align:center;"><b>Please click next to continue</b></div>';
        }, 45000);
    </script>
{% endblock %}

0_otree_app/accounting/templates/accounting/Stage1.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
       Your decision
{% endblock %}

{% block content %}
    <span id="warningt"></span>
    <p></p>
{% if subsession.round_number == 1 %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar" role="progressbar" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ round_number_perc }}%; text-align:center">
            <span style="font-size:12pt;">Period</span>
        </div>
        <div class="progress-bar bg-transparent" role="progressbar" style="width:{{ round_number_perc }}%; text-align:left" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100">
            <span style="font-size:12pt; color:rgb(0, 0, 0);">{{ subsession.round_number }} of {{ Constants.num_rounds }}</span>
        </div>
    </div>
{% else %}
    <div class="progress" style="height: 30px;">
        <div class="progress-bar" role="progressbar" aria-valuenow="{{ round_number_perc }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ round_number_perc }}%; text-align:center">
            <span style="font-size:12pt;">Period {{ subsession.round_number }} of {{ Constants.num_rounds }}</span>
        </div>
    </div>
{% endif %}
    <p></p>
    <div class="instructions">
    <p>
        <b>You</b> (<b>Player 1</b>) have been randomly matched to another participant in this session playing <b>Player 2</b>.<br>
{#        If <b>you</b> choose a value for <b style="color: rgb(0,123,255);">a</b> lower than <b>1.00</b>, then <b>Player 2</b> will choose values for <b>b1</b> and <b>b2</b> ranging from <b>5</b> to <b>15</b> points.<br>#}
        {% if group.e_g == 1 %}
            The value for <b style="color: rgb(0,123,255);">c</b> equals <b style="color: rgb(0,123,255);">{{ group.e_g|floatformat:0 }}</b> point.<br>
        {% else %}
            The value for <b style="color: rgb(0,123,255);">c</b> equals <b style="color: rgb(0,123,255);">{{ group.e_g|floatformat:0 }}</b> points.<br>
        {% endif %}
        <br>
        Now, you can choose a value for <b style="color: rgb(0,123,255);">a</b> ranging from <b>0.00</b> to <b>1.00</b> which impacts the payoffs below.<br>
        If <b>you</b> choose a value for <b style="color: rgb(0,123,255);">a</b> lower than <b>1.00</b>, then <b>Player 2</b> will choose values for <b>b1</b> and <b>b2</b> ranging from <b>5</b> to <b>15</b> points.<br>
    </p>
    <hr>
{#    <p>#}
{#        This leads to the following payoffs in this period:#}
{#    </p>#}
    <b>
    <table>
    <tr>
        <td>
           {% if player.id_in_group == 1 %}
                You (Player 1):  &nbsp;
            {% else %}
                Player 1: &nbsp;
            {% endif %}
        </td>
        <td>
            <span style="color: rgb(0,123,255);" id="demo2">a </span> &times; (15 &minus; {{ group.e_g|floatformat:0 }}) &nbsp;
        </td>
        <td>
            &plus; <span style="color: rgb(0,123,255);" id="demo3">(1 &minus; a)</span> &times; b1
        </td>
        <td style="width: 64px;">
            <span style="color: rgb(0,123,255);" id="demo6"></span>&nbsp;
        </td>
        <td>
            <span style="color: rgb(0,123,255);" id="demo7"></span>
        </td>
    </tr>
    <tr>
        <td>
            {% if player.id_in_group == 2 %}
                You (Player 2):  &nbsp;
            {% else %}
                Player 2: &nbsp;
            {% endif %}
        </td>
        <td>
            <span style="color: rgb(0,123,255);" id="demo4">a</span> &times; 5
        </td>
        <td>
            &plus; <span style="color: rgb(0,123,255);" id="demo5">(1 &minus; a)</span> &times; b2
        </td>
        <td style="width: 64px;">
           <span style="color: rgb(0,123,255);" id="demo8"></span>&nbsp;
        </td>
        <td>
            <span style="color: rgb(0,123,255);" id="demo9"></span>
        </td>
    </tr>
    </table>
    </b>
    </div>
    <p>
        Please drag the slider (or use the left and right arrow keys) to make your choice.
{#        choose a value for <b style="color: rgb(0,123,255);">a</b> ranging from <b>0.00</b> to <b>1.00</b>.<br>#}
    </p>

    {% formfield group.r label=None %}

    <p></p>

    <input type="hidden" name="checkr" value="" id="id_checkr"/>

    {% next_button %}

    <input type="hidden" name="historyc1" value="" id="id_historyc1"/>

{% if subsession.round_number > 1 %}
  <div class="container">
  <button style="color: rgb(255,255,255); background-color: rgb(0,123,255);" type="button" class="btn btn-info" data-toggle="collapse" id="buttonh" data-target="#demo">Click to view history</button>
  <div id="demo" class="collapse">
    <p>
    </p>
 <table class="table">
    <tr>
        <th>Period</th>
        <th>Results</th>
        <th>Payoffs</th>
    </tr>
    {% for p in player.in_previous_rounds %}
        <tr>
            <td>{{ p.round_number }}</td>
            <td>
                <b>c</b> = {{ p.group.e_g|floatformat:0 }}<br>
                <b>a</b> = {{ p.group.r|floatformat:2 }}<br>
                {% if p.group.r == 1 %}
                    {% if player.id_in_group == 1 %}
                        Player 2 could not choose <b>b1</b> and <b>b2</b>
                    {% else %}
                        You could not choose <b>b1</b> and <b>b2</b>
                    {% endif %}
                {% else %}
                    <b>b1</b> = {{ p.group.payoff1|floatformat:2 }}<br>
                    <b>b2</b> = {{ p.group.payoff2|floatformat:2 }}
                {%  endif %}
            </td>
            <td>
            {% if player.id_in_group == 1 %}
                <b>You</b>: {{ p.group.payoff_p1 }}<br>
                <b>Player 2</b>: {{ p.group.payoff_p2 }}
            {% else %}
                <b>Player 1</b>: {{ p.group.payoff_p1 }}<br>
                <b>You</b>: {{ p.group.payoff_p2 }}
            {% endif %}


            </td>
        </tr>
    {% endfor %}
</table>
  </div>
</div>
{% endif %}
{% endblock %}
    {% block scripts %}
    <script>
        $('input[name=r]').on('input', function() {
            var x = $(this).val();
            var x1 = (x * 1).toFixed(2);
            var x2 = (x * (15 -{{ e }})).toFixed(2);
            var x3 = (x * 5).toFixed(2);
            var y = (1 - x).toFixed(2);
            document.getElementById("demo2").innerHTML = x1;
            document.getElementById("demo3").innerHTML = y;
            document.getElementById("demo4").innerHTML = x1;
            document.getElementById("demo5").innerHTML = y;
            document.getElementById("demo6").innerHTML = '<span style="color: rgb(0,0,0);">&equals; </span>' + x2;
            document.getElementById("demo7").innerHTML = '<span style="color: rgb(0,0,0);">&plus; </span>' + y + '<span style="color: rgb(0,0,0);"> &times;</span>' + '<span style="color: rgb(0,0,0);"> b1</span>';
            document.getElementById("demo8").innerHTML = '<span style="color: rgb(0,0,0);">&equals; </span>' + x3;
            document.getElementById("demo9").innerHTML = '<span style="color: rgb(0,0,0);">&plus; </span>' + y + '<span style="color: rgb(0,0,0);"> &times;</span>' + '<span style="color: rgb(0,0,0);"> b2</span>';
            $('#id_checkr').val(1);
        });
    </script>
    <script>
        $('#buttonh').click(function() {
            $('#id_historyc1').val(1);
        });
    </script>
    <script>
        setTimeout(function() {
            document.getElementById("warningt").innerHTML =
                '<div class="progress-bar-2" align="left" style="width: 250px; color: rgb(255,255,255); border-radius: 5px; background-color: rgb(228,28,28); height: 30px; text-align:center;"><b>Please finalize your decision</b></div>';
        }, 60000);
    </script>

{% endblock %}